config/routes.rb
Rails.application.routes.draw do
  #get 'order_items/create'

  #get 'order_items/update'

  #get 'order_items/destroy'

  #get 'carts/show'
  get 'products/srch' => 'products#search'
  get 'products/:id' => 'products#show', as: 'showproduct'

  get 'products/by_cat/:type_id' => 'products#categorized', as:'categories'
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create]
  root to: 'products#index'

  resources :contacts
  get 'about' => 'about_controller#index', as: 'about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :province
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_validation :setorder_status
  belongs_to :order_status
  has_many  :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| (oi.quantity.to_i * oi.unit_price.to_f) }.sum
  end

  private

    def setorder_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type
  has_many :order_items

  paginates_per 3

  mount_uploader :image, ImageUploader
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = session[:grand_total]
    @description = 'Purchase of all cart items.'
  end

  def create
  # Amount in cents
  amount = 500

  @customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  @charge = Stripe::Charge.create(
    :customer    => @customer.id,
    :amount      => amount,
    :description => 'Rails Stripe customer',
    :currency    => 'cad'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base

  def index
    @contact = Contact.first
  end



  private

    def contact_params
      params.require(:contact).permit(:address, :city, :phone, :email, :province_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  def index
    @products = Product.all.page(params[:page]).per(3)
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end

  def categorized
    @products = Product.where(:type_id => params[:type_id]).page(params[:page]).per(3)
    @order_item = current_order.order_items.new
  end

  def search
    @order_item = current_order.order_items.new
   if params[:search]
     value = params[:search]
     @products = Product.where('name LIKE "%' + value + '%"').order("created_at DESC")
     @products = Product.where('description LIKE "%' + value + '%"').order("created_at DESC")

   else
     @products = Product.order("name").page(params[:page]).per(6)
   end
end



  private

    def product_params
      params.require(:product).permit(:name, :description, :price, :stock_quantity, :type_id, :image)
    end

end

app/helpers/about_controller_helper.rb
module AboutControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :province_id %>
    <%= f.text_field :province_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="text-center">
  <h1>Our Contact Information:</h1>

  <div class="col-md-12">
    <div class="well" >
        <p>
          <%= @contact.address %>
        </p>
        <p>
        <%= @contact.city %>, <%= @contact.province.name %>
      </p>
      <p>
        <strong>Phone:</strong> <%= @contact.phone %>
      </p>
      <p>
        <strong>Email:</strong> <%= @contact.email %>
      </p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Province:</strong>
  <%= @contact.province %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :stock_quantity %>
    <%= f.number_field :stock_quantity %>
  </div>

  <div class="field">
    <%= f.label :type_id %>
    <%= f.text_field :type_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-6">
  <div class="well" >
      <h4>
        <%= product.name %></h4>
      </h4>
      <p>
        <strong>Description:</strong>
         <%= product.description %>
      </p>
      <p>
      <strong>Price:</strong> <%= number_to_currency product.price %>
    </p>
    <p>
      <strong>Type:</strong> <%= product.type.name %>
    </p>
      <p>
      <%= image_tag product.image, :size => "200x300" %>
    </p>
  </div>
  <div class="col-md">

    <%= form_for order_item, remote: true do |f| %>
    <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
      <div class="input-group">
        <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
        <div class="input-group-btn">
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.submit "Add to Cart", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-5">
      <h3><%= product.name %></h3>
      <p><%= image_tag product.image, size:'200x300' %></p>
      <p><%= link_to 'View', showproduct_path(product) %></p>
    </div>
    <div class="col-xs-4">
    <br><br><br><br>
      <p><%= product.description %></p>
    </div>
    <div class="col-xs-3">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/categorized.html.erb
<h1 class="text-center">By Category: <%= @products.first.type.name %></h1>
<div class="text-center"><%= paginate @products %></div>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>
<div class="text-center"><%= paginate @products %></div>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/search.html.erb
<h1 class="text-center">Results</h1>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
      <%= render "product_row", product: @product, order_item: @order_item %>
    <p><%= link_to 'Back', products_path %></p>
  </div>
</div>