config/routes.rb
Rails.application.routes.draw do
  #get 'order_items/create'

  #get 'order_items/update'

  #get 'order_items/destroy'

  #get 'carts/show'
  get 'products/srch' => 'products#search'
  get 'products/:id' => 'products#show', as: 'showproduct'

  get 'products/by_cat/:type_id' => 'products#categorized', as:'categories'
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create]
  root to: 'products#index'

  resources :contacts
  get 'about' => 'about_controller#index', as: 'about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :province
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :full_name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_validation :setorder_status
  belongs_to :order_status
  has_many  :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| (oi.quantity.to_i * oi.unit_price.to_f) }.sum
  end

  private

    def setorder_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type
  has_many :order_items

  paginates_per 3

  mount_uploader :image, ImageUploader
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = session[:grand_total]
    @description = 'Purchase of all cart items.'
  end

  def create
  # Amount in cents
  amount = 500

  @customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  @charge = Stripe::Charge.create(
    :customer    => @customer.id,
    :amount      => amount,
    :description => 'Rails Stripe customer',
    :currency    => 'cad'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>
<% session[:grand_total] = current_order.subtotal * 100 %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wonderful Wally's Bottleshop</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">WWBS</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About Us', about_path %></li>
        <li><%= link_to "Contact Us", :controller => :contacts, :action => :index %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Liqueur', categories_path(4) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Liquor', categories_path(3) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Wine', categories_path(2) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Beer', categories_path(1) %></li>
          </ul>
      </ul>

      <ul class="nav navbar-right">
          <li class="cart-text"><%= render 'layouts/cart_text' %></li>
      </ul>
      <form class="navbar-form navbar-right" role="search" action="/products/srch/" method="get">
        <div class="form-group">
          <input type="text" class="form-control" name="search" placeholder="Enter search term here" value="">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>